[tool.pyright]
pythonVersion = "3.13"
strict = ["*"]

[tool.black]
line-length = 120
target-version = ["py313"]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true
force_sort_within_sections = true
line_length = 120
extra_standard_library = "typing_extensions"
lines_after_imports = 2
